comment:
  header: Hi, there.
  footer: "\
    ---\n\n
    > This is an automated comment created by the [peaceiris/actions-label-commenter]. \
    Responding to the bot or mentioning it won't have any effect.\n\n
    [peaceiris/actions-label-commenter]: https://github.com/peaceiris/actions-label-commenter
    "

labels:
  - name: invalid
    labeled:
      issue:
        body: Please follow the issue templates.
        action: close
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close
    unlabeled:
      issue:
        body: Thank you for following the template. The repository owner will reply.
        action: open

  - name: community
    labeled:
      issue:
        body: |
          Please ask questions about the community in the Discord chat.
          https://github.community/c/discord
        action: close

  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close

  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.

  - name: wontfix
      labeled:
        issue:
          body: This will not be worked on but we appreciate your contribution.
          action: close
      unlabeled:
        issue:
          body: This has become active again.
          action: open
