name: auto label

on:
  issues:
    types:
      - opened
      - edited
      - unlabeled
  pull_request_target:
    types:
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@v1
        env:
          RUNNER_DEBUG: 1
